title: Center for Leads Blog
description: >-
  SEO articles about lead buying, lead generation, and sales pipeline growth.
  Learn how to buy qualified leads and grow your business with Center for Leads.

baseurl: "/centerforleads-blog"
url: "https://alfredzero.github.io"

author:
  name: Center for Leads
  email: contact@centerforleads.com

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

show_excerpts: true
